### ISSUE TITLE
Add Socket.io v2 support

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-socketio#77]
Socket.io 2 was recently released.

https://socket.io/

**Comment by eddyystop** [comment]
Socket.IO 2.0.0
13 May 2017 – Damien Arrachequesne (@darrachequesne)
Socket.IO 2.0.0 is finally here! This major release brings several performance improvements:

uws is now the default Websocket engine. It should bring significant improvement in performance (particularly in terms of memory consumption) (release note of Engine.IO)
the Engine.IO and Socket.IO handshake packets were merged, reducing the number of roundtrips necessary to establish a connection. (#2833)
it is now possible to provide a custom parser according to the needs of your application (#2829). Please take a look at the example for more information.
Please note that this release is not backward-compatible, due to:

a breaking change related to utf-8 encoding in engine.io-parser
an update to make the socket id on the client match the id on the server-side (#1058)
Related packages were updated accordingly:

socket.io-redis version 5.x
socket.io-emitter version 3.x

**Comment by daffl** [comment]
This has already been done in https://github.com/feathersjs/feathers-socketio/pull/75 and released as v2.0.0 of this module.
