### ISSUE TITLE
Filter service updates by ID

### ISSUE THREAD

**Issue by nvitas** [feathersjs/feathers-socketio#87]
I'm trying to listen for updates on an 'event' service. I'm trying to listen to just the ones with a specific id.

This will give me all updates:
```
socket.on('event updated', (rEvent) => {
      console.log('Got an updated Event!', rEvent);
});
```

But what I'm looking for is something like this (only event w/id 34):
```
socket.on('event/34 updated', (rEvent) => {
     console.log('Got an updated Event!', rEvent);
});
```

I've gone through the docs, filtering, chat app...I don't have 'users' so I can't join an 'event' service on the user id. I'm struggling w/how to create a room for that specific 'event'.  

What's the best approach for this?

**Comment by daffl** [comment]
Events are cheap and - as long as the client is allowed to see them which is what event filters determine - it is much easier for the client to just ignore it if they don't need it. We recommend not to keep track of the user state on the server because it is pretty bad for performance but to answer your question, you can create a custom event to subscribe to specific ids:

```js
socket.on('subscribe', (service, ids) => {
  socket.feathers.eventSubscriptions = {
    [service]: ids
  };
});
```

Then in a filter on the server:

```js
app.service('event').filter('updated', (data, connection) => {
  if(connection.eventSubscriptions.ids.indexOf(data._id) === -1) {
    return false;
  }

  returnd data;
});
```
